name: Deploy

on:
  push:
    branches:    
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Yarn CLI
      uses: CultureHQ/actions-yarn@v1.0.1
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Deploy to Google Cloud
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: upheld-clone-259000
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: app deploy --quiet
