name: PR

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Yarn CLI
      uses: CultureHQ/actions-yarn@v1.0.1
    - name: Install dependencies
      run: yarn
    - name: Create firebase_account_key.json file
      uses: finnp/create-file-action@master
      env:
        FILE_NAME: "firebase_account_key.json"
        FILE_DATA: ""
    - name: Run eslint
      run: yarn lint
